sem5/WEB/DjangoProject/TravelAgencyApp/TravelAgencyApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls', namespace='login')),
    path('order/', include('order.urls', namespace='order')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('info/', include('info.urls', namespace='info')),
    path('personal_account/', include('personal_account.urls', namespace='personal_account')),
    path('my_statistics/', include('my_statistics.urls', namespace='my_statistics')),
    path('', include('travel.urls', namespace='travel')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sem5/WEB/DjangoProject/TravelAgencyApp/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_trip/<int:trip_id>/', views.cart_add, name='cart_add'),
    path('remove_trip/<int:trip_id>/', views.cart_remove, name='cart_remove'),
]

sem5/WEB/DjangoProject/TravelAgencyApp/personal_account/urls.py
from django.urls import path
from . import views

app_name = 'personal_account'

urlpatterns = [
    path('', views.personal_account, name='personal_account'),
    path('leave_review_view/', views.leave_review_view, name='leave_review_view'),
]

sem5/WEB/DjangoProject/TravelAgencyApp/travel/urls.py
from django.urls import path
from . import views

app_name = 'travel'

urlpatterns = [
    path('', views.list_trips, name='list_trips'),
    path('<int:id>',views.trip_details,name='trip_details'),
    path('edit_trip/<int:id>/',views.edit_trip,name='edit_trip'),
    path('delete_trip/<int:id>/',views.delete_trip,name='delete_trip'),
    path('create_trip/', views.create_trip, name='create_trip'),
    path('<str:trip_country_name>/', views.list_trips,
         name='list_trips_by_country'
         ),
]

sem5/WEB/DjangoProject/TravelAgencyApp/personal_account/models.py
from django.db import models

# Create your models here.

sem5/WEB/DjangoProject/TravelAgencyApp/personal_account/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from info.models import Review


@login_required(login_url='/login/signin/')
def personal_account(request):
    user = request.user
    orders = user.order_set.all()
    return render(request, 'personal_account.html', {'user': user, 'orders': orders})


@login_required(login_url='/login/signin/')
def leave_review_view(request):
    if request.method == 'POST':
        customer = request.user
        content = request.POST.get('review_content')
        rating = request.POST.get('review_rating')
        review = Review(rating=rating, content=content, customer=customer)
        review.save()
        return HttpResponseRedirect(reverse("travel:list_trips"))

sem5/WEB/DjangoProject/TravelAgencyApp/personal_account/templates/personal_account.html
{% extends "base.html" %}
{% load static %}
{% block additional_head %}
<link href="{% static 'css/personal_account.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}Personal Account{% endblock %}

{% block content %}
<p><a href="#review-form">You may leave a review if you want.</a></p>
<form id="searchForm">
    {% csrf_token %}
    <label for="authorInput">Author last name:</label>
    <input type="text" id="authorInput">
    <button type="submit">Search</button>
</form>
<div id="results"></div>
<section>
    <details itemscope itemtype="http://schema.org/Person">
        <summary>
            Your data
        </summary>
        <p>Username: {{ user.username }}</p>
        <p>Email: {{ user.email }}</p>
        <p>First Name: {{ user.first_name }}</p>
        <p>Last Name: {{ user.last_name }}</p>
        <p itemprop="birthDate">Date of Birth: {{ user.date_of_birth }}</p>
        <p itemprop="telephone">Phone Number: {{ user.phone_number }}</p>
    </details>


    <section>
        {% if orders %}
        <details>
            <summary>Orders:</summary>
            <ul>
                {% for order in orders %}
                <li itemscope itemtype="http://schema.org/Order">Order {{ order.id }}, made on {{ order.creation_date }}
                </li>
                <ul>
                    {% for item in order.items.all %}
                    <li itemscope itemtype="http://schema.org/OrderItem">
                        <a href="{% url 'travel:trip_details' item.trip.id %}">
                            <img src="{{ item.trip.image.url }}" alt="{{ item.trip.image }}" width="100" height="100">
                        </a>
                        {{ item.trip }} - {{ item.cost }} - quantity: {{ item.quantity }}
                    </li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </ul>
        </details>

        {% else %}
        <p>No orders.</p>
        {% endif %}
    </section>

    <section>
        <hr>
        <p>You can leave a review.</p>
        <form id="review-form" action="{% url 'personal_account:leave_review_view' %}" method="POST" itemscope
            itemtype="http://schema.org/Review">
            {% csrf_token %}
            <label for="age">Age:</label>
            <input type="number" id="age" name="age" min="18" max="65">
            <br>
            <br>
            <textarea name="review_content" rows="4" cols="50" itemprop="reviewBody" required></textarea>

            <select name="review_rating" itemprop="reviewRating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            <br>
            <input type="checkbox" id="checkbox">
            <label for="checkbox">Checkbox for css</label>
            <br>
            <input type="radio" id="radio1" name="radioGroup" checked>
            <label for="radio1">Radio 1 for css</label>
            <br>
            <input type="radio" id="radio2" name="radioGroup">
            <label for="radio2">Radio 2 for css</label>
            <br>
            <button type="submit" disabled>Submit disabled</button>
            <button type="submit">Submit</button>
        </form>
    </section>

    <hr>
    <hr>
    <button onclick="transposeTable()">Transpose table</button>
    <br>
    <br>
    <button onclick="addRow()">Add row</button>
    <button onclick="addColumn()">Add column</button>
    <br>
    <br>
    <label for="maxCells">Max cells to select in a row/column:</label>
    <input type="number" id="maxCells" min="1" value="1">
    <br>
    <br>
    <label for="tableSize">Table size:</label>
    <input type="number" id="tableSize" min="1" value="4">
    <button onclick="createNewTable()">Create table</button>
    <br>
    <br>
    <table id="myTable"></table>
    <script src="{% static 'js/table.js' %}" defer></script>

    <script src="{% static 'js/personal_account.js' %}" defer></script>
    {% endblock %}